### ISSUE TITLE
Node Dockerfile does not build

### ISSUE THREAD

**Issue by cve** [GaetanRole/symfony-lts-docker-starter#11]
Hi, thanks for sharing probably the most complete Docker solution for Symfony, but I have a problem with building Node (for Encore), my docker-compose.yml:

```yml
# File syntax : https://docs.docker.com/compose/compose-file/
# Global config, you can add your <ENV>.yml to override this one with -f option.

version: "3.6"

services:

  http:
    build: ./docker/nginx
    container_name: starter_nginx
    working_dir: /srv
    restart: on-failure
    depends_on:
      - web-stack

  web-stack:
    build: ./docker/web
    container_name: starter_web_stack
    working_dir: /srv
    restart: on-failure
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: starter_mariadb
    working_dir: /srv
    restart: on-failure

  node:
    build: ./docker/node
    container_name: starter_node
    working_dir: /srv
    restart: on-failure

```

in docker/node/Dockerfile I have:

```Dockerfile
FROM    node:13.10-alpine
LABEL   maintainer="Gaëtan Rolé-Dubruille <gaetan.role@gmail.com>"
RUN     apk add --no-cache su-exec && \
        addgroup bar && \
        adduser -D -h /home -s /bin/sh -G bar foo
RUN     apk add yarn --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ && \
        yarn install
COPY    ./bin/entrypoint.sh /usr/local/bin/entrypoint
RUN     set -o errexit -o nounset -o xtrace; \
        chmod a+x /usr/local/bin/entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint"]
```

but when I run make install - then I that error:

```bash
Step 5/7 : COPY    ./bin/entrypoint.sh /usr/local/bin/entrypoint
ERROR: Service 'node' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder972236022/bin/entrypoint.sh: no such file or directory
make: *** [Makefile:40: build] Błąd 1
```

I tried to change ./bin/entrypoint.sh to another combinations with no luck :(, can You help me with this?
